# ---
# - name: get specific facts from vm
#   hosts: localhost
#   connection: local
#   tasks:
    # - name: get facts from vm
    #   vmware_vm_info:
    #     hostname: vcenter.vlware.local #IP cua vcenter
    #     username: administrator@vsphere.local #Username cua vcenter
    #     password: Suncloud@2022 #Mat khau cua vcenter
    #     validate_certs: no
    #   register: vm_info

    # - name: show msg
    #   debug:
    #     msg: "{{ vm_info.virtual_machines }}"


        
    - name: get fact by vm name
      vmware_guest:
        hostname: vcenter.vlware.local #IP cua vcenter
        username: administrator@vsphere.local #Username cua vcenter
        password: Suncloud@2022 #Mat khau cua vcenter
        validate_certs: no
        datacenter: VLWAREDC  #Ten datacenter
        folder: /
        name: LIN-SERVER-02
      register: facts
    - name: show msg
      debug:
        msg: "{{ facts }}"

---
- name: get specific facts from vm
  hosts: localhost
  connection: local
  tasks:
  - name: Gather facts for vm each properties
    vmware_guest_info:
      hostname: vcenter.vlware.local #IP cua vcenter
      username: administrator@vsphere.local #Username cua vcenter
      password: Suncloud@2022 #Mat khau cua vcenter
      validate_certs: no
      datacenter: VLWAREDC  #Ten datacenter
      folder: /
      name: LIN-SERVER-02
      schema: vsphere
      properties:
        - alarmActionsEnabled
        - overallStatus
        - config.name
        - config.annotation
        - config.flags
        - config.managedBy
        - guest.hostName
        - guest.net
        - summary.storage
        - summary.quickStats
        - summary.config
        - summary.runtime
    register: gather_facts_for_vm_each_properties
  
  - name: show msg
    debug: 
      msg: "{{ gather_facts_for_vm_each_properties }}"
