  - name: Create a Windows Virtual Machine
    vmware_guest:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: no
      name: WIN-tmp-test #Đặt tên cho VM
      cluster: VLWARECL #Tên Cluster
      folder: /
      template: WIN16-TMP #Tên Template muốn clone
      datastore: CTVN-lab # Tên Datastore
      hardware:
        memory_mb: 4096
        num_cpus: 2
        scsi: paravirtual
      networks: #đặt IP Static
        - name: VLAN-21-MGNT
          ip: 10.0.11.130 
          netmask: 255.255.255.0
          gateway: 10.0.11.1
          domain: vlware.local
          dns_servers:
          - 8.8.8.8
          - 1.1.1.1
      customization:
        password: Suncloud@2022!
        dns_servers:
        - 8.8.8.8
        - 10.0.11.254
        timezone: 205 #TIMEZONE VIETNAM 205
        hostname: tmp4 #hostname sẽ đặt cho VM
      wait_for_customization: yes
      wait_for_ip_address: True #play sẽ đợi vCenter dò tìm địa chỉ IP trên máy ảo trước khi hoàn tất.
      state: poweredon
    delegate_to: localhost