---
api_token: 5575898315:AAHJuZqnb678LndGCGSPbDFP9py5ZKd70O0
chat_ID: -970237435

mail_host: mail.suncloud.vn
mail_port: 587
mail_username: support@suncloud.vn
mail_password: 7bpmYRyDrsibpaV


# mail_host: smtp.gmail.com
# mail_port: 587
# mail_username: huykingkong@gmail.com
# mail_password: Duonghuy@@98

# user_to: 
#   # - huydv@suncloud.vn
#   # - huydv398@gmail.com
#   - huykingkong@gmail.com

# SMTP Host: mail.suncloud.vn
# SMTP Port: 587
# SMTP Authentication:
# SMTP Username: support@suncloud.vn
# SMTP Password: 7bpmYRyDrsibpaV
# SMTP SSL Type: SSL